const initState = {
  ratings: [
    {
      id: 1,
      userId: 1,
      productId: 1,
      images: [{ id: 1, path: require('../../assets/images/suvip-removebg-preview.png') }],
      description: 'Tao thấy máy này rất tốt nhưng không nên mua, giá quá rẻ mua không tốn tiền 1 tý nào',
      rate: 2,
      dateComment: '22/10/2023',
    },
    {
      id: 2,
      userId: 1,
      productId: 2,
      images: [{ id: 1, path: require('../../assets/images/suvip-removebg-preview.png') }],
      description: 'Tao thấy máy này rất tốt nhưng không nên mua, giá quá rẻ mua không tốn tiền 1 tý nào',
      rate: 3,
      dateComment: '01/10/2022',
    },
    {
      id: 3,
      userId: 1,
      productId: 3,
      images: [{ id: 1, path: require('../../assets/images/suvip-removebg-preview.png') }],
      description: 'Tao thấy máy này rất tốt nhưng không nên mua, giá quá rẻ mua không tốn tiền 1 tý nào',
      rate: 2,
      dateComment: '03/10/2023',
    },
    {
      id: 4,
      userId: 1,
      productId: 4,
      images: [{ id: 1, path: require('../../assets/images/suvip-removebg-preview.png') }],
      description: 'Tao thấy máy này rất tốt nhưng không nên mua, giá quá rẻ mua không tốn tiền 1 tý nào',
      rate: 3,
      dateComment: '22/01/2023',
    },
    {
      id: 5,
      userId: 1,
      productId: 5,
      images: [{ id: 1, path: require('../../assets/images/suvip-removebg-preview.png') }],
      description: 'Tao thấy máy này rất tốt nhưng không nên mua, giá quá rẻ mua không tốn tiền 1 tý nào',
      rate: 2,
      dateComment: '22/10/2023',
    },
    {
      id: 6,
      userId: 1,
      productId: 6,
      images: [{ id: 1, path: require('../../assets/images/suvip-removebg-preview.png') }],
      description: 'Tao thấy máy này rất tốt nhưng không nên mua, giá quá rẻ mua không tốn tiền 1 tý nào',
      rate: 3,
      dateComment: '22/10/2023',
    },
    {
      id: 7,
      userId: 1,
      productId: 7,
      images: [{ id: 1, path: require('../../assets/images/suvip-removebg-preview.png') }],
      description: 'Tao thấy máy này rất tốt nhưng không nên mua, giá quá rẻ mua không tốn tiền 1 tý nào',
      rate: 2,
      dateComment: '22/10/2023',
    },
    {
      id: 8,
      userId: 1,
      productId: 8,
      images: [{ id: 1, path: require('../../assets/images/suvip-removebg-preview.png') }],
      description: 'Tao thấy máy này rất tốt nhưng không nên mua, giá quá rẻ mua không tốn tiền 1 tý nào',
      rate: 3,
      dateComment: '22/10/2023',
    },
    {
      id: 9,
      userId: 1,
      productId: 9,
      images: [{ id: 1, path: require('../../assets/images/suvip-removebg-preview.png') }],
      description: 'Tao thấy máy này rất tốt nhưng không nên mua, giá quá rẻ mua không tốn tiền 1 tý nào',
      rate: 2,
      dateComment: '22/10/2023',
    },
    {
      id: 10,
      userId: 1,
      productId: 10,
      images: [{ id: 1, path: require('../../assets/images/suvip-removebg-preview.png') }],
      description: 'Tao thấy máy này rất tốt nhưng không nên mua, giá quá rẻ mua không tốn tiền 1 tý nào',
      rate: 3,
      dateComment: '22/10/2023',
    },
    {
      id: 11,
      userId: 1,
      productId: 11,
      images: [{ id: 1, path: require('../../assets/images/suvip-removebg-preview.png') }],
      description: 'Tao thấy máy này rất tốt nhưng không nên mua, giá quá rẻ mua không tốn tiền 1 tý nào',
      rate: 2,
      dateComment: '22/10/2023',
    },
    {
      id: 12,
      userId: 1,
      productId: 8,
      images: [{ id: 1, path: require('../../assets/images/suvip-removebg-preview.png') }],
      description: 'Tao thấy máy này rất tốt nhưng không nên mua, giá quá rẻ mua không tốn tiền 1 tý nào',
      rate: 3,
      dateComment: '22/10/2023',
    },
    {
      id: 13,
      userId: 1,
      productId: 7,
      images: [{ id: 1, path: require('../../assets/images/suvip-removebg-preview.png') }],
      description: 'Tao thấy máy này rất tốt nhưng không nên mua, giá quá rẻ mua không tốn tiền 1 tý nào',
      rate: 2,
      dateComment: '22/10/2023',
    },
    {
      id: 14,
      userId: 1,
      productId: 6,
      images: [{ id: 1, path: require('../../assets/images/suvip-removebg-preview.png') }],
      description: 'Tao thấy máy này rất tốt nhưng không nên mua, giá quá rẻ mua không tốn tiền 1 tý nào',
      rate: 3,
      dateComment: '22/10/2023',
    },
    {
      id: 15,
      userId: 1,
      productId: 5,
      images: [{ id: 1, path: require('../../assets/images/suvip-removebg-preview.png') }],
      description: 'Tao thấy máy này rất tốt nhưng không nên mua, giá quá rẻ mua không tốn tiền 1 tý nào',
      rate: 2,
      dateComment: '22/10/2023',
    },
    {
      id: 16,
      userId: 1,
      productId: 4,
      images: [{ id: 1, path: require('../../assets/images/suvip-removebg-preview.png') }],
      description: 'Tao thấy máy này rất tốt nhưng không nên mua, giá quá rẻ mua không tốn tiền 1 tý nào',
      rate: 3,
      dateComment: '22/10/2023',
    },
    {
      id: 17,
      userId: 1,
      productId: 3,
      images: [{ id: 1, path: require('../../assets/images/suvip-removebg-preview.png') }],
      description: 'Tao thấy máy này rất tốt nhưng không nên mua, giá quá rẻ mua không tốn tiền 1 tý nào',
      rate: 2,
      dateComment: '22/10/2023',
    },
    {
      id: 18,
      userId: 2,
      productId: 2,
      images: [{ id: 1, path: require('../../assets/images/suvip-removebg-preview.png') }],
      description:
        'Máy dùng rất chán, nhanh nóng mà chụp ảnh các thứ không được đẹp. Máy dùng rất chán, nhanh nóng mà chụp ảnh các thứ không được đẹp',
      rate: 3,
      dateComment: '22/10/2023',
    },
    {
      id: 19,
      userId: 3,
      productId: 2,
      images: [{ id: 1, path: require('../../assets/images/suvip-removebg-preview.png') }],
      description: 'Trải nhiệm cực tệ. Giá thì đắt mà chất lượng không ra một cái gì luôn.',
      rate: 2,
      dateComment: '22/10/2023',
    },
    {
      id: 20,
      userId: 2,
      productId: 2,
      images: [{ id: 1, path: require('../../assets/images/suvip-removebg-preview.png') }],
      description:
        'Chất lượng quá bình thường so với số tiền bỏ ra. Khuyến cáo không nên mua máy này. Chất lượng quá bình thường so với số tiền bỏ ra. Khuyến cáo không nên mua máy này ',
      rate: 3,
      dateComment: '22/10/2023',
    },
  ],
};

const RatingReducer = (state = initState, action) => {
  return state;
};
export default RatingReducer;
