export const GET_LIST_USERS = 'GET_LIST_USERS';
export const GET_SINGLE_USER = 'GET_SINGLE_USER';
export const GET_SINGLE_USER_NOT_FOUND = 'GET_SINGLE_USER_NOT_FOUND';
export const GET_LIST_RESOURCE = 'GET_LIST_RESOURCE';
export const GET_SINGLE_RESOURCE = 'GET_SINGLE_RESOURCE';
export const GET_SINGLE_RESOURCE_NOT_FOUND = 'GET_SINGLE_RESOURCE_NOT_FOUND';
export const POST_CREATE = 'POST_CREATE';
export const PUT_UPDATE = 'PUT_UPDATE';
export const PATCH_UPDATE = 'PATCH_UPDATE';
export const DELETE_DELETE = 'DELETE_DELETE';
export const POST_REGISTER_SUCCESSFUL = 'POST_REGISTER_SUCCESSFUL';
export const POST_REGISTER_UNSUCCESSFUL = 'POST_REGISTER_UNSUCCESSFUL';
export const POST_LOGIN_SUCCESSFUL = 'POST_LOGIN_SUCCESSFUL';
export const POST_LOGIN_UNSUCCESSFUL = 'POST_LOGIN_UNSUCCESSFUL';
export const GET_DELAYED_RESPONSE = 'GET_DELAYED_RESPONSE';
export const API_CONSTANTS = [
  GET_LIST_USERS,
  GET_SINGLE_USER,
  GET_SINGLE_USER_NOT_FOUND,
  GET_LIST_RESOURCE,
  GET_SINGLE_RESOURCE,
  GET_SINGLE_RESOURCE_NOT_FOUND,
  GET_DELAYED_RESPONSE,
  POST_CREATE,
  PUT_UPDATE,
  PATCH_UPDATE,
  DELETE_DELETE,
  POST_REGISTER_SUCCESSFUL,
  POST_REGISTER_UNSUCCESSFUL,
  POST_LOGIN_SUCCESSFUL,
  POST_LOGIN_UNSUCCESSFUL,
];
export const FETCH_GET_SINGLE_USER_REQUEST = 'FETCH_GET_SINGLE_USER_REQUEST';
export const FETCH_GET_SINGLE_USER_SUCCESS = 'FETCH_GET_SINGLE_USER_SUCCESS';
export const FETCH_GET_SINGLE_USER_FAILURE = 'FETCH_GET_SINGLE_USER_FAILURE';

export const FETCH_GET_LIST_USERS_REQUEST = 'FETCH_GET_LIST_USERS_REQUEST';
export const FETCH_GET_LIST_USERS_SUCCESS = 'FETCH_GET_LIST_USERS_SUCCESS';
export const FETCH_GET_LIST_USERS_FAILURE = 'FETCH_GET_LIST_USERS_FAILURE';

export const FETCH_GET_SINGLE_USER_NOT_FOUND_REQUEST = 'FETCH_GET_SINGLE_USER_NOT_FOUND_REQUEST';
export const FETCH_GET_SINGLE_USER_NOT_FOUND_SUCCESS = 'FETCH_GET_SINGLE_USER_NOT_FOUND_SUCCESS';
export const FETCH_GET_SINGLE_USER_NOT_FOUND_FAILURE = 'FETCH_GET_SINGLE_USER_NOT_FOUND_FAILURE';

export const FETCH_GET_LIST_RESOURCE_REQUEST = 'FETCH_GET_LIST_RESOURCE_REQUEST';
export const FETCH_GET_LIST_RESOURCE_SUCCESS = 'FETCH_GET_LIST_RESOURCE_SUCCESS';
export const FETCH_GET_LIST_RESOURCE_FAILURE = 'FETCH_GET_LIST_RESOURCE_FAILURE';

export const FETCH_GET_SINGLE_RESOURCE_REQUEST = 'FETCH_GET_SINGLE_RESOURCE_REQUEST';
export const FETCH_GET_SINGLE_RESOURCE_SUCCESS = 'FETCH_GET_SINGLE_RESOURCE_SUCCESS';
export const FETCH_GET_SINGLE_RESOURCE_FAILURE = 'FETCH_GET_SINGLE_RESOURCE_FAILURE';

export const FETCH_GET_SINGLE_RESOURCE_NOTFOUND_REQUEST = 'FETCH_GET_SINGLE_RESOURCE_NOTFOUND_REQUEST';
export const FETCH_GET_SINGLE_RESOURCE_NOTFOUND_SUCCESS = 'FETCH_GET_SINGLE_RESOURCE_NOTFOUND_SUCCESS';
export const FETCH_GET_SINGLE_RESOURCE_NOTFOUND_FAILURE = 'FETCH_GET_SINGLE_RESOURCE_NOTFOUND_FAILURE';

export const FETCH_GET_DELAYED_RESPONSE_REQUEST = 'FETCH_GET_DELAYED_RESPONSE_REQUEST';
export const FETCH_GET_DELAYED_RESPONSE_SUCCESS = 'FETCH_GET_DELAYED_RESPONSE_SUCCESS';
export const FETCH_GET_DELAYED_RESPONSE_FAILURE = 'FETCH_GET_DELAYED_RESPONSE_FAILURE';

export const FETCH_POST_CREATE_REQUEST = 'FETCH_POST_CREATE_REQUEST';
export const FETCH_POST_CREATE_SUCCESS = 'FETCH_POST_CREATE_SUCCESS';
export const FETCH_POST_CREATE_FAILURE = 'FETCH_POST_CREATE_FAILURE';

export const FETCH_PUT_UPDATE_REQUEST = 'FETCH_PUT_UPDATE_REQUEST';
export const FETCH_PUT_UPDATE_SUCCESS = 'FETCH_PUT_UPDATE_SUCCESS';
export const FETCH_PUT_UPDATE_FAILURE = 'FETCH_PUT_UPDATE_FAILURE';

export const FETCH_PATCH_UPDATE_REQUEST = 'FETCH_PATCH_UPDATE_REQUEST';
export const FETCH_PATCH_UPDATE_SUCCESS = 'FETCH_PATCH_UPDATE_SUCCESS';
export const FETCH_PATCH_UPDATE_FAILURE = 'FETCH_PATCH_UPDATE_FAILURE';

export const FETCH_DELETE_DELETE_REQUEST = 'FETCH_DELETE_DELETE_REQUEST';
export const FETCH_DELETE_DELETE_SUCCESS = 'FETCH_DELETE_DELETE_SUCCESS';
export const FETCH_DELETE_DELETE_FAILURE = 'FETCH_DELETE_DELETE_FAILURE';

export const FETCH_REGISTER_SUCCESSFUL_REQUEST = 'FETCH_REGISTER_SUCCESSFUL_REQUEST';
export const FETCH_REGISTER_SUCCESSFUL_SUCCESS = 'FETCH_REGISTER_SUCCESSFUL_SUCCESS';
export const FETCH_REGISTER_SUCCESSFUL_FAILURE = 'FETCH_REGISTER_SUCCESSFUL_FAILURE';

export const FETCH_REGISTER_UNSUCCESSFUL_REQUEST = 'FETCH_REGISTER_UNSUCCESSFUL_REQUEST';
export const FETCH_REGISTER_UNSUCCESSFUL_SUCCESS = 'FETCH_REGISTER_UNSUCCESSFUL_SUCCESS';
export const FETCH_REGISTER_UNSUCCESSFUL_FAILURE = 'FETCH_REGISTER_UNSUCCESSFUL_FAILURE';

export const FETCH_POST_LOGIN_SUCCESSFUL_REQUEST = 'FETCH_POST_LOGIN_SUCCESSFUL_REQUEST';
export const FETCH_POST_LOGIN_SUCCESSFUL_SUCCESS = 'FETCH_POST_LOGIN_SUCCESSFUL_SUCCESS';
export const FETCH_POST_LOGIN_SUCCESSFUL_FAILURE = 'FETCH_POST_LOGIN_SUCCESSFUL_FAILURE';

export const FETCH_POST_LOGIN_UNSUCCESSFUL_REQUEST = 'FETCH_POST_LOGIN_UNSUCCESSFUL_REQUEST';
export const FETCH_POST_LOGIN_UNSUCCESSFUL_SUCCESS = 'FETCH_POST_LOGIN_UNSUCCESSFUL_SUCCESS';
export const FETCH_POST_LOGIN_UNSUCCESSFUL_FAILURE = 'FETCH_POST_LOGIN_UNSUCCESSFUL_FAILURE';

export const PATH_GET_LIST_USERS = 'https://reqres.in/api/users?page=2';
export const PATH_GET_SINGLE_USER = 'https://reqres.in/api/users/2';
export const PATH_GET_SINGLE_USER_NOT_FOUND = 'https://reqres.in/api/users/23';
export const PATH_GET_LIST_RESOURCE = 'https://reqres.in/api/unknown';
export const PATH_GET_SINGLE_RESOURCE = 'https://reqres.in/api/unknown/2';
export const PATH_GET_SINGLE_RESOURCE_NOT_FOUND = 'https://reqres.in/api/unknown/23';
export const PATH_POST_CREATE = 'https://reqres.in/apy/users';
export const PATH_PUT_UPDATE = 'https://reqres.in/api/users/2';
export const PATH_PATCH_UPDATE = 'https://reqres.in/api/users/2';
export const PATH_DELETE_DELETE = 'https://reqres.in/api/users/2';
export const PATH_POST_REGISTER_SUCCESSFUL = 'https://reqres.in/api/register';
export const PATH_POST_REGISTER_UNSUCCESSFUL = 'https://reqres.in/api/register';
export const PATH_POST_LOGIN_SUCCESSFUL = 'https://reqres.in/api/login';
export const PATH_POST_LOGIN_UNSUCCESSFUL = 'https://reqres.in/api/login';
export const PATH_GET_DELAYED_RESPONSE = 'https://reqres.in/api/users?delay=3';
